export const libraryList = [
    "d3.js",
    "altair",
    "vega",
    "apache_echarts",
    "chart.js",
    "seaborn",
    "recharts",
    "victory",
    "c3.js",
    "matplotlib",
    "bokeh",
    "highcharts",
    "plotly",
  ];
  export const tagList = [
    "bar",
    "line",
    "pie",
    "scatter",
    "map",
    "candlestick",
    "boxplot",
    "heatmap",
    "tree",
    "static",
    "interactive",
    "linear_regression",
    "geography",
    "business",
    "themed",
    "machine_learning",
  ];

  export const availableTagList = [...libraryList, ...tagList]
